DeveloperAcademy-POSTECH/MacC-Team13-SplitIt

SplitIt/Presenter/MyInfo/PayData.swift, SplitIt/Presenter/MyInfo/SocialPay.swift, SplitIt/Presenter/MyInfo/User.swift, SplitIt/Presenter/MyInfo/UserData.swift, SplitIt/Presenter/MyInfo/View/MyInfoVC.swift, SplitIt/Presenter/MyInfo/ViewModel/MyInfoVM.swift
1. MyInfoVC 구현
2. MyInfoVM 구현
- #29
Close #29
=> [Feat/#29] MyInfoVC, MyInfoVM 구현했음

SplitIt/Presenter/MyInfo/View/MyInfoVC.swift, SplitIt/Presenter/MyInfoDetail/MemberLog/View/MemberLogVC.swift, SplitIt/Presenter/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift, SplitIt/Presenter/MyInfoDetail/MyAccountBank/View/PayButton.swift
1. MyInfoVC를 수정 작업 
2. MyBankAccountVM 수정 작업
1. PayButton.swfit 수정 작업
- #77 
|MyInfoVC|MyBankAccountVM|
|---|---|
|![Simulator Screenshot - iPhone 14 - 2023-10-22 at 21 15 33](https://github.com/DeveloperAcademy-POSTECH/MacC-Team13-SplitIt/assets/91787174/9e6f7783-094d-472d-8f4e-c92ed1b114c7)|![Simulator Screenshot - iPhone 14 - 2023-10-22 at 21 15 47](https://github.com/DeveloperAcademy-POSTECH/MacC-Team13-SplitIt/assets/91787174/c34cebd7-b257-41f7-ac93-9ed8b04a26dd)|
- 몇몇 코드는 이해가 힘들어서 수정하지 못하였음.
Close #77
=> [Design/#77] MyInfoVC MyInfoDetail vcs design detail

SplitIt/Presenter/SplitCreateFlow/CSMember/View/CSMemberInputVC.swift, SplitIt/Presenter/SplitCreateFlow/CSTitle/View/CSTitleInputVC.swift, SplitIt/Presenter/SplitCreateFlow/CSTotalAmount/View/CSTotalAmountInputVC.swift, SplitIt/Presenter/SplitCreateFlow/ExclItemCycle/ExclItemName/View/ExclItemNameInputVC.swift, SplitIt/Presenter/SplitCreateFlow/ExclItemCycle/ExclItemPrice/View/ExclItemPriceInputVC.swift
1. 아래 항목들의 '여기에 사용을 돕는 문구가 들어가요' 영역에 UX Writing 추가
- CSTitleInputVC.swift 수정
- CSTotalAmountVC.swift 수정
- CSMemberInputVC.swift 수정
- ExlItemNameVC.swift 수정
- ExlItemPriceinputVC.swift 수정
- #92 
Close #92
=> [Design/#92] Create Flow 각 TextField 하단의 UX Writing을 수정하였습니다.

SplitIt/Presenter/Home/View/HomeVC.swift
1. 홈화면에서 CSEditListVC 이동하는 코드 주석처리 하였습니다.
- #103 
Close #103
=> [Fix/#103] 홈화면에서 CSEditListVC 이동하는 코드 주석처리 하였습니다.

SplitIt/Presenter/History/View/Cell/HistorySplitCell.swift, SplitIt/Presenter/History/View/HistorySectionHeader.swift, SplitIt/Presenter/History/View/HistoryVC.swift, SplitIt/Presenter/History/ViewModel/HistoryVM.swift
1. HistoryView Design Detail
- #119 
Close #119
=> Design/#119 HistoryView Design 작업을 완료하였습니다.

SplitIt.xcodeproj/project.pbxproj, SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/MemberCheck.swift, SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/CSMemberSearchVC.swift, SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/CSMemberVC.swift, SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/Cell/CSMemberCell.swift, SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/Cell/SearchCell.swift, SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/Cell/SelectedCell.swift, SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/ViewModel/CSMemberSearchVM.swift, SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/ViewModel/CSMemberVM.swift, SplitIt/Repository/SplitRepository.swift
1. 선택된 CSMember를 보는 View를 구현하였습니다.
2. CSMember Search 및 선택하는 View를 구현하였습니다.
- #128
Close #128
=> Feat/#128 CSMemberSearchView 구현하였습니다.

SplitIt/Presenter/Home/View/HomeVC.swift
1. Design/#146 HomeView Design 기기대응 완료하였습니다
- #146 
Close #146
=> Design/#146 HomeView Design 기기대응 완료하였습니다

SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemInput/View/ExclItemInputVC.swift, SplitIt/Presenter/SplitShare/ViewModel/SplitShareVM.swift
1. 차수 종료 시 Realm update 
2. splitShareView fetch 수정하였습니다.
- #168 
Close #168
=> Chore/#168 차수 종료 시 Realm update 및 splitShareView fetch 수정하였습니다.

SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/Cell/CSMemberCell.swift, SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/Cell/SelectedCell.swift, SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/ViewModel/CSMemberSearchVM.swift, SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/ViewModel/CSMemberVM.swift, SplitIt/Repository/SplitRepository.swift, SplitIt/Resources/Components/SPNavigationBar.swift
1. CSMemberSearchView 예외처리 수정
2. CSMemberView 보더 없애기
3. SPNavigationBar Y축 중심 맞추기 수정
4. SPNavigationBar 1/n 일때 이미지 2개만 되도록 수정
- #164 
Close #164
=> [Design/#164] CSMemberSearchView 수정하였습니다.

SplitIt.xcodeproj/project.pbxproj, SplitIt.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, SplitIt/Presenter/History/View/HistoryVC.swift, SplitIt/Presenter/History/ViewModel/HistoryVM.swift, SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/CSMemberVC.swift, SplitIt/Presenter/SplitShare/View/Cell/SplitShareTableCell.swift, SplitIt/Presenter/SplitShare/View/SplitShareSectionFooter.swift, SplitIt/Presenter/SplitShare/View/SplitShareSectionHeader.swift, SplitIt/Presenter/SplitShare/View/SplitShareVC.swift, SplitIt/Presenter/SplitShare/ViewModel/SplitShareVM.swift, SplitIt/Resources/Extensions/UITableView+.swift
1. ShareView Design Detail 수정하였습니다.
- #172 
Close #172
=> [Design/#172] ShareView Design Detail 수정하였습니다.

SplitIt/Repository/SplitRepository.swift
1. Edit Flow Method 만들고 확인 완료하였습니다.
- #188 
Close #188
=> [Fix/#188] Edit Flow Method 만들고 확인 완료하였습니다.

SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/CSMemberVC.swift, SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/ViewModel/CSMemberSearchVM.swift, SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/ViewModel/CSMemberVM.swift
1. csMemberSearchView 정산자가 MemberLog에 포함되던 문제 해결
2. csMemberView에서 tableView를 탭할 시에도 MemberSearchView가 팝업되도록 수정
- #191 
Close #191
=> Fix/#191 csMemberSearchView 정산자가 MemberLog에 포함되던 문제를 해결하였습니다.

SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/CSMemberSearchVC.swift
1. csMemberSearchView에서 키보드가 올라올 때 tableView가 가려지던 현상 수정
- #194 
Close #194
=> Fix/#194 csMemberSearchView에서 키보드가 올라올 때 tableView가 가려지던 현상을 수정하였습니다.

SplitIt.xcodeproj/project.pbxproj, SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/ViewModel/CSMemberSearchVM.swift, SplitIt/Resources/Utility/HapticManager.swift
1. HapticManager 구현
2.  csMemberSearchView에 햅틱 적용
- #196 
Close #196
=> [Feat/#196] HapticManager를 구현하고 csMemberSearchView에 적용하였습니다.

SplitIt/Presenter/History/View/Cell/HistorySplitCell.swift, SplitIt/Presenter/History/ViewModel/HistorySplitCellVM.swift, SplitIt/Resources/Components/SPNavigationBar.swift
1. navigationBar X버튼이 상황에 따라 다르게 동작하도록 수정
- #219 
Close #219
=> [Fix/#219] navigationBar를 수정하였습니다.

SplitIt/Resources/Components/SPNavigationBar.swift
1. NavigationBar 버튼 탭 시 색상이 변경되도록 수정
- #223 
Close #223
=> Fix/#223 NavigationBar 버튼 탭 시 색상이 변경되도록 수정하였습니다.

SplitIt.xcodeproj/project.pbxproj, SplitIt.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, SplitIt/Presenter/History/View/HistoryVC.swift, SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/View/Cell/SelectedCell.swift, SplitIt/Presenter/SplitCreateFlow/CSMemberSearch/ViewModel/CSMemberSearchVM.swift, SplitIt/Presenter/SplitShare/View/SplitShareVC.swift, SplitIt/Presenter/SplitShare/ViewModel/SplitShareVM.swift, SplitIt/Repository/SplitRepository.swift
1. HistoryView에서 하단의 패딩을 0으로 맞췄습니다.
2. SplitShareVC에서 정산 결과 공유 시, 간편 페이 정보 전달이 되지 않던 부분을 수정하였습니다.
3. SplitShareVM에서 필요 없던 로직을 삭제하고 전체적으로 깔끔한 코드가 될 수 있도록 수정하였습니다.
4. History, SplitShare의 header top constraint를 8로 수정하였습니다.
5. SplitMethodView와 관련된 모든 사항은 추후 완전한 디자인 변경이 있을 예정이므로 수정하지 않았습니다.
6. memberSearchView, Repository에서 nickname과 관련 있던 부분을 모두 수정하였습니다.
7. Realm의 버전이 최신버전과 맞지않았던 문제를 해결하였습니다.
- #247 
Close #247
=> Fix/#247 QA에서 발견한 문제점을 수정하였습니다.

SplitIt/Presenter/HistoryFlow/ViewModel/HistoryVM.swift, SplitIt/Presenter/Home/ViewModel/HomeVM.swift, SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift, SplitIt/Presenter/SplitCreateFlow/CSInfo/ViewModel/CSInfoVM.swift, SplitIt/Presenter/SplitCreateFlow/CSMember/View/CSMemberVC.swift, SplitIt/Presenter/SplitCreateFlow/CSMember/ViewModel/CSMemberVM.swift, SplitIt/Presenter/SplitCreateFlow/SplitMethodSelect/View/SplitMethodSelectVC.swift, SplitIt/Presenter/SplitShare/View/SplitShareVC.swift, SplitIt/Repository/SplitRepository.swift, SplitIt/Resources/Components/SPNavigationBar.swift
1. 필요에 따라 Flow별 header를 바꿔주도록 하였습니다.
- #321 
Close #321
=> Fix/#321 필요에 따라 Flow별 header를 바꿔주도록 하였습니다.

SplitIt/Presenter/HistoryFlow/View/Cell/HistorySplitCell.swift, SplitIt/Presenter/HistoryFlow/View/HistorySectionHeader.swift, SplitIt/Presenter/HistoryFlow/View/HistoryVC.swift, SplitIt/Presenter/SplitCreateFlow/CSMember/View/CSMemberVC.swift, SplitIt/Presenter/SplitCreateFlow/CSMember/ViewModel/CSMemberVM.swift, SplitIt/Presenter/SplitShare/View/SplitShareVC.swift, SplitIt/Repository/SplitRepository.swift, SplitIt/Resources/Components/SPTextField.swift
1.  history 뷰의 디자인 수정
2. splitShare 뷰의 버튼 수정
3. textField 앞뒤 공백 처리
- #323 
Close #323
=> Design/#323 history 뷰의 디자인을 수정하였습니다.

SplitIt/Presenter/SplitCreateFlow/CSMember/ViewModel/CSMemberVM.swift, SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/ExclItemInfoAddModalVC.swift, SplitIt/Presenter/SplitCreateFlow/ExclItem/ExclItemModal/View/ExclItemInfoEditModalVC.swift, SplitIt/Presenter/SplitEditFlow/EditCSDetails/EditCSInfo/View/EditCSInfoVC.swift, SplitIt/Presenter/SplitShare/View/Cell/SplitShareTableCell.swift, SplitIt/Presenter/SplitShare/View/SplitShareSectionFooter.swift, SplitIt/Presenter/SplitShare/View/SplitShareSectionHeader.swift, SplitIt/Presenter/SplitShare/View/SplitShareVC.swift, SplitIt/Presenter/SplitShare/ViewModel/SplitShareVM.swift, SplitIt/Resources/Extensions/UIFont+.swift, SplitIt/Resources/Extensions/UILabel+.swift
1. 영수증의 디자인 디테일 수정
2. csMember의 검색 기록 추가 로직 수정 -> 검색시 바로 검색기록에 추가
3. exclItem 커스텀 키보드 00 추가
4. custom UIFont 구조체에서 enum으로 수정
- #327
Close #327
=> Fix/#327 출시 전 기타 수정사항들을 수정합니다.

SplitIt/Presenter/HistoryFlow/ViewModel/HistoryVM.swift, SplitIt/Presenter/Home/ViewModel/HomeVM.swift, SplitIt/Presenter/SplitCreateFlow/SplitMethodSelect/View/SplitMethodSelectVC.swift, SplitIt/Presenter/SplitShare/View/SplitShareVC.swift
1. splitshare 버튼 디자인 및 팝업 로직을 수정하였습니다.
- #336 
Close #336
=> Fix/#336 splitshare 버튼 디자인 및 팝업 로직을 수정하였습니다.

SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MemberLog/Cell/MemberCell.swift, SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MemberLog/View/MemberLogVC.swift
1. tableView 간격 수정 완료했습니다.
- #351 
Close #351
=> [Design/#351] 디자인 QA tableView 간격 수정 완료했습니다.

SplitIt/Presenter/SplitCreateFlow/CSMember/View/CSMemberVC.swift, SplitIt/Presenter/SplitCreateFlow/CSMember/View/Cell/CSMemberSelectedCell.swift, SplitIt/Presenter/SplitCreateFlow/CSMember/ViewModel/CSMemberVM.swift, SplitIt/Presenter/SplitEditFlow/EditCSDetails/EditCSMember/View/EditCSMemberVC.swift, SplitIt/Presenter/SplitEditFlow/EditCSDetails/EditCSMember/ViewModel/EditCSMemberVM.swift, SplitIt/Presenter/SplitShare/View/SplitShareVC.swift
1. 디자인 QA 적용
- #355 
Close #355
=> Design/#355 디자인 QA 적용 완료하였습니다.

SplitIt/Presenter/MyInfoFlow/MyInfo/View/MyInfoVC.swift, SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MemberLog/Cell/MemberCell.swift, SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift
1. 디자인 QA 수정 완료했습니다.
- #357 
Close #357
=> [Design/#357] 디자인 QA 수정 완료했습니다.

SplitIt/Presenter/MyInfoFlow/MyInfo/View/MyInfoVC.swift
1. 디자인QA 수정 완료했습니다.
- #357 
Close #357
=> 수정 완료했습니다.

SplitIt/Presenter/MyInfoFlow/MyInfo/View/MyInfoVC.swift, SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MyAccountBank/View/MyBankAccountVC.swift, SplitIt/Presenter/MyInfoFlow/MyInfoDetail/MyAccountBank/ViewModel/MyBankAccountVM.swift
1. MyBankAccount 코드 리팩토링했습니다.
- #364 
Close #364
=> [Fix/#364] 코드 리팩토링했습니다.
